<?php
/**
 * Class implementing the required settings for the plugin.
 *
 * @link       https://BrianHenry.ie
 * @since      1.0.0
 *
 * @package    BH_WP_AWS_SES_Bounce_Handler
 * @subpackage BH_WP_AWS_SES_Bounce_Handler/includes
 */

namespace BrianHenryIE\AWS_SES_Bounce_Handler\API;

use BrianHenryIE\AWS_SES_Bounce_Handler\WP_Logger\API\Logger_Settings_Interface;
use Psr\Log\LogLevel;


/**
 * The plugin settings.
 *
 * @since      1.0.0
 * @package    BH_WP_AWS_SES_Bounce_Handler
 * @subpackage BH_WP_AWS_SES_Bounce_Handler/includes
 * @author     BrianHenryIE <BrianHenryIE@gmail.com>
 */
class Settings implements Settings_Interface, Logger_Settings_Interface {

	/**
	 * List of ARNs which have successfully been confirmed with AWS SNS.
	 *
	 * @return string[]
	 */
	public function get_confirmed_arns(): array {
		return get_option( self::CONFIRMED_ARNS, array() );
	}

	/**
	 * Add an ARN string to the list of confirmed ARNs and save the option.
	 *
	 * @param string $arn AWS SNS ARN.
	 */
	public function set_confirmed_arn( string $arn ): void {
		$confirmed_arns   = $this->get_confirmed_arns();
		$confirmed_arns[] = $arn;
		update_option( self::CONFIRMED_ARNS, array_unique( $confirmed_arns ) );
	}

	/**
	 * Return the secret key autogenerated on plugin activation, which must be present in all
	 * requests or the REST endpoint will disregard them.
	 *
	 * @return string
	 */
	public function get_secret_key(): string {
		return get_option( self::SECRET_KEY );
	}

	/**
	 * The full endpoint URL: https://brianhenry.ie/wp-json/brianhenryie/v1/aws-ses/?secret=autogend.
	 *
	 * @return string
	 */
	public function get_endpoint(): string {
		return get_rest_url( null, 'brianhenryie/v1/aws-ses/?secret=' . $this->get_secret_key() );
	}

	/**
	 * @return string
	 * @see LogLevel
	 */
	public function get_log_level(): string {
		return LogLevel::INFO;
	}

	/**
	 * For friendly display.
	 *
	 * @return string
	 */
	public function get_plugin_name(): string {
		return 'AWS SES Bounce Handler';
	}

	/**
	 * For filenames and URLs.
	 *
	 * @return string
	 */
	public function get_plugin_slug(): string {
		return 'bh-wp-aws-ses-bounce-handler';
	}

	public function get_plugin_basename(): string {
		return 'bh-wp-aws-ses-bounce-handler/bh-wp-aws-ses-bounce-handler.php';
	}

	public function get_plugin_version(): string {
		return '1.3.2';
	}
}
